#!/usr/bin/python
# -*- coding:utf-8 -*-
import sys
import zhuaxia.config as config
import zhuaxia.util as util
import logging
import zhuaxia.log as log

if __name__ == '__main__':
    logger_name = 'zxLogger'

    #load config
    if not config.load_config():
        print 'xx'
    
    log.setup_log(logger_name, config.LOG_LVL_CONSOLE, config.LOG_LVL_FILE)

    LOG = log.get_logger(logger_name)

    LOG.error(u"test error")
    LOG.info("test info")
    LOG.warn("test warn")
    print "============"
    log.test_hl()

