#!/bin/python
# -*- coding:utf-8 -*-
import sys
import zhuaxia.config as config
import zhuaxia.util as util
import logging
import zhuaxia.log as log
import zhuaxia.xiami as xm
import zhuaxia.downloader as downloader
import zhuaxia.commander as commander

if __name__ == '__main__':
    logger_name = 'zxLogger'

    #load config
    config.load_config()
    log.setup_log(logger_name, config.LOG_LVL_CONSOLE, config.LOG_LVL_FILE)
    LOG = log.get_logger(logger_name)

    #test input file
    #commander.shall_I_begin('/tmp/in.txt', True)
    commander.shall_I_begin('http://www.xiami.com/space/lib-song/u/25531126')
