#!/bin/python
# -*- coding:utf-8 -*-
import sys
import zhuaxia.config as config
import zhuaxia.util as util
import logging
import zhuaxia.log as log
import zhuaxia.xiami as xm
import zhuaxia.downloader as downloader

if __name__ == '__main__':
    logger_name = 'zxLogger'

    #load config
    if not config.load_config():
        print 'xx'
    
    log.setup_log(logger_name, config.LOG_LVL_CONSOLE, config.LOG_LVL_FILE)

    LOG = log.get_logger(logger_name)

    print 'user:' + config.XIAMI_LOGIN_EMAIL
    print 'pwd:' +config.XIAMI_LOGIN_PASSWORD

    xiami_obj = xm.Xiami(config.XIAMI_LOGIN_EMAIL,config.XIAMI_LOGIN_PASSWORD,'/tmp/test/xm.cookie')
    song = xm.Song(xiami_obj,url='http://www.xiami.com/song/1769901638')
    LOG.info( song.filename)
    LOG.info(song.dl_link)
    LOG.info(song.abs_path)
    downloader.download(song)

    #album = xm.Album(xiami_obj, 'http://www.xiami.com/album/253320')

    #for s in album.songs:
        #print s.song_name


    #LOG.error(u"test error")
    #LOG.info("test info")
    #LOG.warn("test warn")
    #print "============"
    #log.test_hl()

